In [6]:
import sys
print(sys.executable)

c:\Users\Pooja\AppData\Local\Programs\Python\Python39\python.exe

In [7]:
import	pandas as pd
import numpy as np
print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 1.3.2
Numpy version: 1.21.2

In [8]:
df =pd.read_csv(
    "../data/APl_logistics.csv",
    encoding="latin1"
)
print("Dataset loaded successfully.")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully.
Rows: 180519
Columns: 40

In [9]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [10]:
print("Total columns:", len(df.columns))
for i,col	in enumerate(df.columns,1):
				print(f"{i}. {col}")

Total columns: 40
1. Type
2. Days for shipping (real)
3. Days for shipment (scheduled)
4. Benefit per order
5. Sales per customer
6. Delivery Status
7. Late_delivery_risk
8. Category Id
9. Category Name
10. Customer City
11. Customer Country
12. Customer Fname
13. Customer Id
14. Customer Lname
15. Customer Segment
16. Customer State
17. Customer Street
18. Customer Zipcode
19. Department Id
20. Department Name
21. Latitude
22. Longitude
23. Market
24. Order City
25. Order Country
26. Order Customer Id
27. Order Item Discount
28. Order Item Discount Rate
29. Order Item Product Price
30. Order Item Profit Ratio
31. Order Item Quantity
32. Sales
33. Order Item Total
34. Order Profit Per Order
35. Order Region
36. Order State
37. Order Status
38. Product Name
39. Product Price
40. Shipping Mode

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Fname                 180519 non-null  object
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  object
 14  Customer Segment               180519 non-null  object
 15  Customer State                 180519 non-null  object
 16  Customer Street                180519 non-null  object
 17  Customer Zipcode               180516 non-null  float64
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  object
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  object
 23  Order City                     180519 non-null  object
 24  Order Country                  180519 non-null  object
 25  Order Customer Id              180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  object
 35  Order State                    180519 non-null  object
 36  Order Status                   180519 non-null  object
 37  Product Name                   180519 non-null  object
 38  Product Price                  180519 non-null  float64
 39  Shipping Mode                  180519 non-null  object
dtypes: float64(13), int64(8), object(19)
memory usage: 55.1+ MB

In [12]:
missing = df.isnull().sum()
missing	= missing[missing > 0].sort_values(ascending=False)
missing

Customer Lname      8
Customer Zipcode    3
dtype: int64

In [13]:
print("duplicate rows:", df.duplicated().sum())

duplicate rows: 0

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Days for shipping (real),180519.0,3.497654,1.623722,0.000000,2.000000,3.000000,5.000000,6.000000
Days for shipment (scheduled),180519.0,2.931847,1.374449,0.000000,2.000000,4.000000,4.000000,4.000000
Benefit per order,180519.0,21.974989,104.433526,-4274.980000,7.000000,31.520000,64.800000,911.800000
Sales per customer,180519.0,183.107607,120.043668,7.490000,104.380000,163.990000,247.400000,1939.990000
Late_delivery_risk,180519.0,0.548291,0.497664,0.000000,0.000000,1.000000,1.000000,1.000000
Category Id,180519.0,31.851451,15.640064,2.000000,18.000000,29.000000,45.000000,76.000000
Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Customer Zipcode,180516.0,35921.126914,37542.461122,603.000000,725.000000,19380.000000,78207.000000,99205.000000
Department Id,180519.0,5.443460,1.629246,2.000000,4.000000,5.000000,7.000000,12.000000
Latitude,180519.0,29.719955,9.813646,-33.937553,18.265432,33.144863,39.279617,48.781933
Longitude,180519.0,-84.915675,21.433241,-158.025986,-98.446312,-76.847908,-66.370583,115.263077
Order Customer Id,180519.0,6691.379495,4162.918106,1.000000,3258.500000,6457.000000,9779.000000,20757.000000
Order Item Discount,180519.0,20.664741,21.800901,0.000000,5.400000,14.000000,29.990000,500.000000
Order Item Discount Rate,180519.0,0.101668,0.070415,0.000000,0.040000,0.100000,0.160000,0.250000
Order Item Product Price,180519.0,141.232547,139.732489,9.990000,50.000000,59.990000,199.990000,1999.990000
Order Item Profit Ratio,180519.0,0.120647,0.466796,-2.750000,0.080000,0.270000,0.360000,0.500000
Order Item Quantity,180519.0,2.127638,1.453451,1.000000,1.000000,1.000000,3.000000,5.000000
Sales,180519.0,203.772092,132.273075,9.990000,119.980000,199.920000,299.950000,1999.990000
Order Item Total,180519.0,183.107607,120.043668,7.490000,104.380000,163.990000,247.400000,1939.990000
Order Profit Per Order,180519.0,21.974989,104.433526,-4274.980000,7.000000,31.520000,64.800000,911.800000
Product Price,180519.0,141.232547,139.732489,9.990000,50.000000,59.990000,199.990000,1999.990000

In [15]:
df[
    [
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Late_delivery_risk",
				]
].describe()

,Days for shipping (real),Days for shipment (scheduled),Late_delivery_risk
count,180519.000000,180519.000000,180519.000000
mean,3.497654,2.931847,0.548291
std,1.623722,1.374449,0.497664
min,0.000000,0.000000,0.000000
25%,2.000000,2.000000,0.000000
50%,3.000000,4.000000,1.000000
75%,5.000000,4.000000,1.000000
max,6.000000,4.000000,1.000000

In [16]:
print(
    df["Late_delivery_risk"].value_counts()
)

1    98977
0    81542
Name: Late_delivery_risk, dtype: int64

In [17]:
df["Shipping Mode"].value_counts()

Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: Shipping Mode, dtype: int64

In [18]:
print("MARKETS")
print(df["Market"].value_counts())

print("\nORDER REGIONS")
print(df["Order Region"].value_counts())

MARKETS
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: Market, dtype: int64

ORDER REGIONS
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: Order Region, dtype: int64

In [19]:
print("MARKETS")
print(df["Market"].value_counts)

MARKETS
<bound method IndexOpsMixin.value_counts of 0         Pacific Asia
1                LATAM
2                LATAM
3                 USCA
4                 USCA
              ...
180514    Pacific Asia
180515    Pacific Asia
180516    Pacific Asia
180517    Pacific Asia
180518    Pacific Asia
Name: Market, Length: 180519, dtype: object>

In [20]:
print("\nORDER REGIONS")
print(df["Order Region"].value_counts())

ORDER REGIONS
Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: Order Region, dtype: int64

In [21]:
print("\nORDER COUNTRIES")
print(df["Order Country"].value_counts().head(20))

ORDER COUNTRIES
Estados Unidos          24840
Francia                 13222
México                  13172
Alemania                 9564
Australia                8497
Brasil                   7987
Reino Unido              7302
China                    5758
Italia                   4989
India                    4783
Indonesia                4204
España                   3868
El Salvador              3726
República Dominicana     3669
Honduras                 3629
Cuba                     3534
Turquía                  3395
Nicaragua                3046
Guatemala                2778
Nigeria                  2309
Name: Order Country, dtype: int64

In [22]:
print("Number of Markets:",df["Market"].nunique())
print("Number of Regions:",df["Order Region"].nunique())
print("Number of Countries:",df["Order Country"].nunique())

Number of Markets: 5
Number of Regions: 23
Number of Countries: 164

In [23]:
print("Markets:")
for value in df["Market"].unique():
    print(repr(value))

Markets:
'Pacific Asia'
'LATAM'
'USCA'
'Europe'
'Africa'

In [24]:
print("\nRegions:")
for value in df["Order Region"].unique():
 print(repr(value))

Regions:
'South Asia'
'Central America'
'East of USA'
'Southern Europe'
'Western Europe'
'Oceania'
'South America'
'West Asia'
'West Africa'
'Caribbean'
'US Center '
'Central Africa'
'Southeast Asia'
'Northern Europe'
'Eastern Asia'
'South of  USA '
'Southern Africa'
'West of USA '
'Eastern Europe'
'Canada'
'East Africa'
'North Africa'
'Central Asia'

In [25]:
print("SHIPPING MODES")
print(df["Shipping Mode"].value_counts())

SHIPPING MODES
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: Shipping Mode, dtype: int64

In [26]:
print(df["Market"].value_counts)

<bound method IndexOpsMixin.value_counts of 0         Pacific Asia
1                LATAM
2                LATAM
3                 USCA
4                 USCA
              ...
180514    Pacific Asia
180515    Pacific Asia
180516    Pacific Asia
180517    Pacific Asia
180518    Pacific Asia
Name: Market, Length: 180519, dtype: object>

In [27]:
print(df["Order Region"].value_counts())

Central America    28341
Western Europe     27109
South America      14935
Oceania            10148
Northern Europe     9792
Southeast Asia      9539
Southern Europe     9431
Caribbean           8318
West of USA         7993
South Asia          7731
Eastern Asia        7280
East of USA         6915
West Asia           6009
US Center           5887
South of  USA       4045
Eastern Europe      3920
West Africa         3696
North Africa        3232
East Africa         1852
Central Africa      1677
Southern Africa     1157
Canada               959
Central Asia         553
Name: Order Region, dtype: int64

In [28]:
print("SHIPPING MODES")
print(df["Shipping Mode"].value_counts())

SHIPPING MODES
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: Shipping Mode, dtype: int64

In [29]:
print("Number of Shipping Modes:",df["Shipping Mode"].nunique())

Number of Shipping Modes: 4

In [30]:
print("Shipping Modes:")
for value in df["Shipping Mode"].unique():
    print(repr(value))

Shipping Modes:
'Standard Class'
'Same Day'
'First Class'
'Second Class'

In [31]:
pd.crosstab(
    df["Shipping Mode"],
    df["Late_delivery_risk"]
)

Late_delivery_risk      0      1
Shipping Mode
First Class          1301  26513
Same Day             5283   4454
Second Class         8229  26987
Standard Class      66729  41023

In [32]:
df_clean = df.copy()
print("Original rows:",len(df))
print("Working rows:",len(df_clean))

Original rows: 180519
Working rows: 180519

In [33]:
duplicate_count = df_clean.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [34]:
missing = df_clean.isnull().sum()
missing = missing[missing>0].sort_values(ascending=False)
print(missing)

Customer Lname      8
Customer Zipcode    3
dtype: int64

In [35]:
critical_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Delivery Status",
    "Late_delivery_risk",
    "Shipping Mode",
    "Market",
    "Order Region",
    "Order Country",
    "Customer Segment"
]

df_clean[critical_columns].isnull().sum()

Days for shipping (real)         0
Days for shipment (scheduled)    0
Delivery Status                  0
Late_delivery_risk               0
Shipping Mode                    0
Market                           0
Order Region                     0
Order Country                    0
Customer Segment                 0
dtype: int64

In [36]:
print("Actual shipping days:")
print(df_clean["Days for shipping (real)"].describe())

print("\nScheduled shipping days:")
print(df_clean["Days for shipment (scheduled)"].describe())

Actual shipping days:
count    180519.000000
mean          3.497654
std           1.623722
min           0.000000
25%           2.000000
50%           3.000000
75%           5.000000
max           6.000000
Name: Days for shipping (real), dtype: float64

Scheduled shipping days:
count    180519.000000
mean          2.931847
std           1.374449
min           0.000000
25%           2.000000
50%           4.000000
75%           4.000000
max           4.000000
Name: Days for shipment (scheduled), dtype: float64

In [37]:
actual_negative =(
    df_clean["Days for shipping (real)"] < 0
).sum()
scheduled_negative = (
    df_clean["Days for shipment (scheduled)"] < 0
).sum()
print("Negative actual shipping days:",actual_negative)
print("Negative scheduled shipping days:",scheduled_negative)

Negative actual shipping days: 0
Negative scheduled shipping days: 0

In [5]:
print(
    df_clean[
        [
            "Days for shipping (real)",
            "Days for shipment (scheduled)",
            "Late_delivery_risk"
								]
				].dtypes
)

NameError: name 'df_clean' is not defined

In [40]:
import pandas as pd
import numpy as pd

In [42]:
import pandas 
import numpy
pd = pandas
np = numpy
print("pd=",pd.__name__)
print("np=",np.__name__)

pd= pandas
np= numpy

In [46]:
df = pd.read_csv(
    "../data/APL_Logistics.csv"	,
    encoding="latin1"
)
print("Dataset loaded successfully!")
print(df.shape)

Dataset loaded successfully!
(180519, 40)

In [49]:
df = pd.read_csv(
    "../data/Apl_Logistics.csv",
    encoding="latin1"
)
print("Dataset loaded:",df.shape)

Dataset loaded: (180519, 40)

In [51]:
df_clean = df.copy()
print("Clean dataset created:",df_clean.shape)

Clean dataset created: (180519, 40)

In [52]:
df_clean["Days for shipping (real)"]=pd.to_numeric(
    df_clean["Days for shipping (real)"],
    errors="coerce"
)
df_clean["Days for shipment (scheduled)"]=pd.to_numeric(
    df_clean["Days for shipment (scheduled)"],
    errors="coerce"
)
df_clean["Late_delivery_risk"]=pd.to_numeric(
    df_clean["Late_delivery_risk"],
    errors="coerce"
)

In [54]:
print(
    df_clean[
        [
            "Days for shipping (real)",
            "Days for shipment (scheduled)",
            "Late_delivery_risk"
								]
				].dtypes
)

Days for shipping (real)         int64
Days for shipment (scheduled)    int64
Late_delivery_risk               int64
dtype: object

In [55]:
df_clean[
    [
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Late_delivery_risk"
				]
].isnull().sum()

Days for shipping (real)         0
Days for shipment (scheduled)    0
Late_delivery_risk               0
dtype: int64

In [60]:
text_columns =[
    "Market",
    "Order Region",
    "Order Country",
    "Shipping Mode",
    "Customer Segment",
    "Delivery Status",
    "Order Status"
]

for col in text_columns:
    df_clean[col]=df_clean[col].astype("string").str.strip()

In [61]:
print("Markets:")
print(df_clean["Market"].unique())
print("/nShipping Modes:")
print(df_clean["Shipping Mode"].unique())

Markets:
<StringArray>
['Pacific Asia', 'LATAM', 'USCA', 'Europe', 'Africa']
Length: 5, dtype: string
/nShipping Modes:
<StringArray>
['Standard Class', 'Same Day', 'First Class', 'Second Class']
Length: 4, dtype: string

In [62]:
print("/nRegions:")
print(df_clean["Order Region"].unique())

/nRegions:
<StringArray>
[     'South Asia', 'Central America',     'East of USA', 'Southern Europe',
  'Western Europe',         'Oceania',   'South America',       'West Asia',
     'West Africa',       'Caribbean',       'US Center',  'Central Africa',
  'Southeast Asia', 'Northern Europe',    'Eastern Asia',   'South of  USA',
 'Southern Africa',     'West of USA',  'Eastern Europe',          'Canada',
     'East Africa',    'North Africa',    'Central Asia']
Length: 23, dtype: string

In [63]:
print(
    df_clean["Late_delivery_risk"].value_counts(
        dropna=False
				)
)

1    98977
0    81542
Name: Late_delivery_risk, dtype: int64

In [67]:
df_clean["Delay_Gap"]=(
    df_clean["Days for shipping (real)"]
   - df_clean["Days for shipment (scheduled)"]
)

In [68]:
df_clean[
    [
        "Days for shipping (real)",
        "Days for shipment (scheduled)",
        "Delay_Gap"
				]
].head(10)

   Days for shipping (real)  Days for shipment (scheduled)  Delay_Gap
0                         6                              4          2
1                         4                              4          0
2                         4                              4          0
3                         6                              4          2
4                         6                              4          2
5                         6                              4          2
6                         4                              4          0
7                         4                              4          0
8                         4                              4          0
9                         4                              4          0

In [69]:
df_clean["Delivery_performance"]=np.select(
    [
        df_clean["Delay_Gap"]<0,
        df_clean["Delay_Gap"]==0,
        df_clean["Delay_Gap"]>0
				],
                [
                    "Early",
                    "On_Time",
                    "Delayed"
																],
                                                                default="Unkonwn"
)

In [71]:
df_clean["Delivery_performance"].value_counts()

Delayed    103400
Early       43366
On_Time     33753
Name: Delivery_performance, dtype: int64

In [72]:
pd.crosstab(
    df_clean["Delivery_performance"],
    df_clean["Late_delivery_risk"]
)

Late_delivery_risk        0      1
Delivery_performance
Delayed                4423  98977
Early                 43366      0
On_Time               33753      0

In [73]:
print("Final rows:",len(df_clean))
print("Final columns:",len(df_clean.columns))
print("\nMissing critical values:")
print(
    df_clean[critical_columns].isnull().sum()
)
print("\nDuplicates:")
print(df_clean.duplicated().sum())
print("\nDelivery performance:")
print(df_clean["Delivery_performance"].value_counts())
print("\nDelay Gap:")
print(df_clean["Delay_Gap"].describe())

Final rows: 180519
Final columns: 42

Missing critical values:
Days for shipping (real)         0
Days for shipment (scheduled)    0
Delivery Status                  0
Late_delivery_risk               0
Shipping Mode                    0
Market                           0
Order Region                     0
Order Country                    0
Customer Segment                 0
dtype: int64

Duplicates:
0

Delivery performance:
Delayed    103400
Early       43366
On_Time     33753
Name: Delivery_performance, dtype: int64

Delay Gap:
count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Delay_Gap, dtype: float64

In [74]:
df_clean.to_csv(
    "../outputs/cleaned_data/APL_Logistics_Cleaned.csv",
    index=False
)
print("Cleaned dataset saved successffully!")

Cleaned dataset saved successffully!

In [75]:
print(df_clean["Delivery_performance"].value_counts())

Delayed    103400
Early       43366
On_Time     33753
Name: Delivery_performance, dtype: int64

In [76]:
print(df_clean["Delay_Gap"].describe())

count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Delay_Gap, dtype: float64

In [77]:
print(df_clean[critical_columns].isnull().sum())

Days for shipping (real)         0
Days for shipment (scheduled)    0
Delivery Status                  0
Late_delivery_risk               0
Shipping Mode                    0
Market                           0
Order Region                     0
Order Country                    0
Customer Segment                 0
dtype: int64